version: '3.5'

services:
  registry:
    image: registry:2.8.1
    ports:
    - "5000:5000"
    env_file: 
      - env/registry.env
    volumes:
      - registry_data:/var/lib/registry
      - cert_data:/cert
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  docker-registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: docker-registry-ui
    restart: always
    ports:
    - "5001:80"
    environment:
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 5000

volumes:
  registry_data:
  cert_data:
