---
- name: Lab
  hosts: all
  become: True

  tasks:
    - name: Ensure pwgen is installed
      apt:
        name: pwgen
        state: present
        update_cache: True
        
    - name: Generate password
      shell: pwgen -N 1 -s 30
      register: mypass

    - name: Print the generated password
      debug:
        msg: "The password is {{ mypass.stdout }}"

    - name: List all files and directories in /home/ansible
      shell: ls -a /home/vagrant
      register: dir_contents

    - name: Print directory contents using loops
      debug:
        msg: "{{ item }}"
      loop: "{{ dir_contents.stdout_lines }}"

    - name: Print dir_contents
      debug:
        msg: "{{ dir_contents }}"
