---
- name: PackStack
  hosts: all
  become: true
  become_method: sudo
  tasks:

    - name: Upgrade all packages
      dnf:
        name: "*"
        state: latest
    
    - name: Enable Powertools
      command:
        cmd: dnf config-manager --enable powertools
        warn: false

    - name: Disable epel
      command:
        cmd: dnf config-manager --disable epel
        warn: false

    - name: Uninstall Hiera but keep its dependencies
      dnf:
        name: hiera
        state: absent
        autoremove: yes

    - name: Install all the packages
      dnf:
        name: '{{ item }}'
        state: present
        update_cache: True
      with_items:
        - centos-release-openstack-yoga
        - dhclient
        - openstack-packstack
        - network-scripts

    - name: Disable service firewalld 
      ansible.builtin.systemd:
        name: firewalld
        enabled: no
        state: stopped

    - name: Disable service NetworkManager
      ansible.builtin.systemd:
        name: NetworkManager
        enabled: no

    - name: Enable service network 
      ansible.builtin.systemd:
        name: network
        # state: restarted
        enabled: yes
    #     masked: no

    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled

    - name: Reboot host and wait for it to restart
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami

    - name: Install PackStack
      command:
        cmd: packstack --allinone
        warn: false
