version: '3.8'
services:
  nginx:
    image: nginx-tunado
    ports:
      - 80:80
  mysql:
    image: mysql
    # ports:
    #   - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
volumes:
  nginx:
  mysql: