- name: helm add repo
  shell: helm repo add prometheus-community {{ url_repo_helm }}
  register: prometheus_add_repo

- name: helm update
  shell: helm repo update
  register: prrometheus_repo_update

- name: Instalando o Prometheus Operator
  shell: helm install prometheus prometheus-community/kube-prometheus-stack
  register: prometheus_install