---
- hosts: all
  become: yes
  remote_user: vagrant
  tasks:
  - name: Instalando o NginX
    apt: 
      name: nginx
      state: latest
      update_cache: yes

  - name: Habilitando o start do nginx no boot 
    service: 
      name: nginx
      enable: yes

  - name: Iniciando o nginx
    service:
      name: nginx
      state: started

  - name: copiando index
    copy:
      src: index.html
      dest: /var/www/html/index.html

  - name: nginx.conf copy
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
    notify: Restartando o NginX

  handlers:
  - name: Restartando o NginX
    service:
      name: nginx
      state: restarted
