---
# vars file for install-monit-tools
# url_repo_helm: https://kubernetes-charts.storage.googleapis.com
url_repo_helm: https://charts.bitnami.com/bitnami
deploy_prometheus: "meu-querido-prometheus bitnami/kube-prometheus"
