---
- name: Atualização e Reboot RHEL & Debian derivados Linux distros
  hosts: all
  vars:
    reboot_connect_timeout: 5
    reboot_post_reboot_delay: 15
    reboot_timeout: 600
  tasks:

    - name: Upgrade RHEL Family OS packages
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Update repositories cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest
      when: ansible_os_family == "Debian"

    - name: Upgrade the OS (apt-get dist-upgrade)
      apt:
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Reboot host
      reboot:
        connect_timeout: "{{ reboot_connect_timeout }}"
        post_reboot_delay: "{{ reboot_post_reboot_delay }}"
        reboot_timeout: "{{ reboot_timeout }}"