- hosts: all
  # become: yes
  # user: vagrant
  gather_facts: no
  pre_tasks:
  roles: 
  - { role: common, tags: ["pre_tasks"]}
  - { role: install-k8s, tags: ["install_k8s_role"] }    
  # roles:

- hosts: k8s-masters
  # become: yes
  # user: vagrant
  roles: 
    - { role: create-cluster, tags: ["create_cluster_role"] }
  
- hosts: k8s-workers
  # become: yes
  # user: vagrant
  roles: 
  - { role: join-workers, tags: ["join_workers_role"] }

- hosts: k8s-masters
  # become: yes
  # user: vagrant
  roles: 
  - { role: install-helm, tags: ["install_helm3_role"]}

- hosts: k8s-masters
  # become: yes
  # user: vagrant
  roles: 
  - { role: install-monit-tools, tags: ["install_monit_tools"]}